### ISSUE TITLE
AKO should expose its cleanup status publicly

### ISSUE THREAD

**Issue by maplain** [vmware/load-balancer-and-ingress-services-for-kubernetes#175]
After `deleteConfig` is set to True, AKO will clean up all the resources it manages and stops reconciling. There is NO way for an external component who instructed AKO's clean up to know the current state.

It must be supported so the external component could safely move forward once it knows reliably AKO has finished all its work.

**Comment by sudswasavi** [comment]
To tackle this problem,  we could(and probably will) do the following implementation:

- The statefulset of the AKO pod should set the `ownerrefence` field on the configmap to itself. This should be configurable via helm.

- When the AKO pod boots up, check if deleteconfig is set to false. If yes, then set a finaliser on the configmap that prohibits garbage collection of the configmap.

- At any point in time, if the user flips the deleconfig to true, then AKO will first delete all the objects in the Avi Controller and removes the finaliser string from the configmap. This will denote to the clients that AKO does not have any configuration set in the Avi Controller.

- If in this state, the deleteconfig flag is set to false again, AKO should set the finaliser string and do a re-sync. The re-sync part is done today already.

- If the liveness probe is shutdown due to reason like - 'unable to contact the controller', 'invalid configuration' etc, AKO should remove the finaliser string from the configmap, leaving it free for garbage collection.

**Comment by sudswasavi** [comment]
As it turns out, the statefulsets are created `after` the configmaps are created and hence the owner reference logic will not work here. We would instead consider providing a CRD object with the status field. Currently we are considering converting the entire configmap of AKO into a CRD.

**Comment by sudswasavi** [comment]
This is taken care of with this PR: https://github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/pull/190 

The end user managing the AKO pod can monitor the StatefulSet conditions to get information object deletion on the controller and take a call based on that.

**Comment by maplain** [comment]
For reference:
This is the condition type: https://github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/blame/master/internal/lib/constants.go#L102
This is the message in the condition: https://github.com/vmware/load-balancer-and-ingress-services-for-kubernetes/blame/master/internal/lib/constants.go#L105
